services:
  aria2-ariang:
    image: hurlenko/aria2-ariang
    container_name: dusbox-aria2-ariang
    restart: unless-stopped
    ports:
      - "443:443"
    env_file: .env
    volumes:
      - ./data:/aria2/data
      - ./conf:/aria2/conf
      - ./caddy/Caddyfile:/usr/local/caddy/Caddyfile
      - ./caddy/data:/root/.local/share/caddy
      - ./start.sh:/aria2/start.sh

  filebrowser:
    image: filebrowser/filebrowser
    container_name: dusbox-filebrowser
    volumes:
      - ./data:/srv
      - ./filebrowser/database.db:/database.db
      - ./filebrowser/config.json:/.filebrowser.json
