services:
  aria2-ariang:
    image: hurlenko/aria2-ariang:1.3.7
    container_name: dusbox-aria2-ariang
    restart: unless-stopped
    ports:
      - "443:443"
    env_file: .env
    volumes:
      - ./aria2-ariang/data:/aria2/data
      - ./aria2-ariang/conf:/aria2/conf
      - ./caddy/Caddyfile:/usr/local/caddy/Caddyfile
      - ./caddy/data:/root/.local/share/caddy
      - ./start.sh:/aria2/start.sh

  filebrowser:
    image: filebrowser/filebrowser:v2.31.1
    container_name: dusbox-filebrowser
    restart: unless-stopped
    volumes:
      - ./aria2-ariang/data:/data
      - ./filebrowser/database.db:/database.db
      - ./filebrowser/config.json:/.filebrowser.json

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.9.11
    container_name: dusbox-jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - ./jellyfin/config:/config
      - ./aria2-ariang/data:/data
    ports:
      - 8096:8096
    restart: unless-stopped
